/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package gov.deajcesar.judisafese.presentation;

import gov.deajcesar.judisafese.logic.GListPerson;
import gov.deajcesar.judisafese.logic.GPerson;
import gov.deajcesar.judisafese.logic.GRegister;
import gov.deajcesar.judisafese.logic.Utility;
import java.io.IOException;
import java.util.Date;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.persistence.NoResultException;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author jairo
 */
public class IFReporteCC extends javax.swing.JInternalFrame {
    private DefaultTableModel model;
    private String titulos[]={"Fecha", "Hora", "Temp","Sintomas", "Origen", "Destino", "     Observacion    "};
    private String datos[][]={null,null, null,null,null};
    private JFPrincipal contenedor;
    
    /**
     * Creates new form IFReporte
     */
    public IFReporteCC() {
        initComponents();
        this.model = new DefaultTableModel(datos, titulos);
        this.table.setModel(this.model);
        this.table.getColumn("Fecha").setPreferredWidth(10);
        this.table.getColumn("Hora").setPreferredWidth(10);
        this.table.getColumn("Temp").setPreferredWidth(10);
        this.lTotal.setVisible(false);
        this.lValorTotal.setVisible(false);
    }

    public void setContenedor(JFPrincipal contenedor) {
        this.contenedor = contenedor;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        fInicio = new javax.swing.JFormattedTextField();
        jLabel2 = new javax.swing.JLabel();
        fFin = new javax.swing.JFormattedTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        table = new javax.swing.JTable();
        jButton1 = new javax.swing.JButton();
        lTotal = new javax.swing.JLabel();
        lValorTotal = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        tCc = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        tName = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        tPhone = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        tEmail = new javax.swing.JTextField();
        tLastName = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        tAddres = new javax.swing.JTextField();
        jButton2 = new javax.swing.JButton();
        bExportar = new javax.swing.JButton();
        jLabel16 = new javax.swing.JLabel();
        tBirthDay = new javax.swing.JTextField();

        setTitle("Reportes de ingreso");
        setPreferredSize(new java.awt.Dimension(1051, 726));

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        jLabel1.setText("Fecha Inicio (*) : ");

        fInicio.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        fInicio.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.DateFormatter()));
        fInicio.setToolTipText("dd/mm/yyyy");
        fInicio.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        fInicio.setPreferredSize(new java.awt.Dimension(60, 28));
        fInicio.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                fInicioFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                fInicioFocusLost(evt);
            }
        });
        fInicio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fInicioActionPerformed(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        jLabel2.setText("Fecha Fin (*) : ");

        fFin.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        fFin.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.DateFormatter()));
        fFin.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        fFin.setPreferredSize(new java.awt.Dimension(60, 28));
        fFin.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                fFinFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                fFinFocusLost(evt);
            }
        });
        fFin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fFinActionPerformed(evt);
            }
        });

        table.setAutoCreateRowSorter(true);
        table.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        table.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        table.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null}
            },
            new String [] {
                "No Documento", "Nombre", "Apellido", "Temperatura", "Sintomas", "Origen", "Destino", "Observacion"
            }
        ));
        table.setAutoResizeMode(javax.swing.JTable.AUTO_RESIZE_ALL_COLUMNS);
        jScrollPane1.setViewportView(table);

        jButton1.setText("Buscar");
        jButton1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jButton1.setPreferredSize(new java.awt.Dimension(35, 28));
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        lTotal.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lTotal.setText("Registros encontrados:");

        lValorTotal.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lValorTotal.setText("jLabel4");

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        jLabel3.setText("No Documento : ");

        tCc.setBackground(new java.awt.Color(255, 255, 204));
        tCc.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        tCc.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        tCc.setPreferredSize(new java.awt.Dimension(70, 28));
        tCc.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                tCcFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                tCcFocusLost(evt);
            }
        });
        tCc.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tCcActionPerformed(evt);
            }
        });
        tCc.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                tCcKeyPressed(evt);
            }
            public void keyReleased(java.awt.event.KeyEvent evt) {
                tCcKeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                tCcKeyTyped(evt);
            }
        });

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        jLabel4.setText("Nombres (*) : ");

        tName.setEditable(false);
        tName.setBackground(new java.awt.Color(248, 251, 230));
        tName.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        tName.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        tName.setPreferredSize(new java.awt.Dimension(60, 28));
        tName.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                tNameFocusGained(evt);
            }
        });
        tName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tNameActionPerformed(evt);
            }
        });

        jLabel5.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        jLabel5.setText("No celular: ");

        tPhone.setEditable(false);
        tPhone.setBackground(new java.awt.Color(248, 251, 230));
        tPhone.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        tPhone.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        tPhone.setPreferredSize(new java.awt.Dimension(60, 28));
        tPhone.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                tPhoneFocusGained(evt);
            }
        });
        tPhone.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tPhoneActionPerformed(evt);
            }
        });

        jLabel6.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        jLabel6.setText("Dir. residencia: ");

        jLabel7.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        jLabel7.setText("Email:");

        tEmail.setEditable(false);
        tEmail.setBackground(new java.awt.Color(248, 251, 230));
        tEmail.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        tEmail.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        tEmail.setPreferredSize(new java.awt.Dimension(60, 28));
        tEmail.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                tEmailFocusGained(evt);
            }
        });
        tEmail.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tEmailActionPerformed(evt);
            }
        });

        tLastName.setEditable(false);
        tLastName.setBackground(new java.awt.Color(248, 251, 230));
        tLastName.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        tLastName.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        tLastName.setPreferredSize(new java.awt.Dimension(60, 28));
        tLastName.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                tLastNameFocusGained(evt);
            }
        });
        tLastName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tLastNameActionPerformed(evt);
            }
        });

        jLabel8.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        jLabel8.setText("Apellido  (*) : ");

        tAddres.setBackground(new java.awt.Color(248, 251, 230));
        tAddres.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        tAddres.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        tAddres.setPreferredSize(new java.awt.Dimension(60, 28));
        tAddres.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                tAddresFocusGained(evt);
            }
        });
        tAddres.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tAddresActionPerformed(evt);
            }
        });

        jButton2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gov/deajcesar/judisafese/resources/tmp.png"))); // NOI18N
        jButton2.setText("Ingresos por Tmp");
        jButton2.setIconTextGap(10);
        jButton2.setPreferredSize(new java.awt.Dimension(163, 40));
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        bExportar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gov/deajcesar/judisafese/resources/excel.png"))); // NOI18N
        bExportar.setText("Exportar");
        bExportar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bExportarActionPerformed(evt);
            }
        });

        jLabel16.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        jLabel16.setText("Edad :");

        tBirthDay.setEditable(false);
        tBirthDay.setBackground(new java.awt.Color(248, 251, 230));
        tBirthDay.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        tBirthDay.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        tBirthDay.setPreferredSize(new java.awt.Dimension(60, 28));
        tBirthDay.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                tBirthDayFocusGained(evt);
            }
        });
        tBirthDay.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tBirthDayActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 126, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel16))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addComponent(tName, javax.swing.GroupLayout.DEFAULT_SIZE, 300, Short.MAX_VALUE)
                                    .addComponent(tEmail, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(tBirthDay, javax.swing.GroupLayout.DEFAULT_SIZE, 300, Short.MAX_VALUE))
                                .addGap(53, 53, 53)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel8)
                                    .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 121, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(tPhone, javax.swing.GroupLayout.PREFERRED_SIZE, 348, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(tAddres, javax.swing.GroupLayout.PREFERRED_SIZE, 348, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(tLastName, javax.swing.GroupLayout.PREFERRED_SIZE, 348, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane1)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(lTotal)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(lValorTotal, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(bExportar)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 177, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel1)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(fInicio, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(fFin, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jLabel3)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(tCc, javax.swing.GroupLayout.PREFERRED_SIZE, 165, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 184, Short.MAX_VALUE)))
                        .addContainerGap())))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(8, 8, 8)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, 29, Short.MAX_VALUE)
                    .addComponent(fInicio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, 29, Short.MAX_VALUE)
                    .addComponent(fFin, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(tCc, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(15, 15, 15)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(1, 1, 1)
                                .addComponent(tName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(tBirthDay, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jLabel16)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel7)
                            .addComponent(tEmail, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(tLastName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(tPhone, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(tAddres, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel6))))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 456, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lTotal)
                            .addComponent(lValorTotal)))
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(bExportar, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void fInicioFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_fInicioFocusGained
        // TODO add your handling code here:
        
    }//GEN-LAST:event_fInicioFocusGained

    private void fInicioFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_fInicioFocusLost
        // TODO add your handling code here:
    }//GEN-LAST:event_fInicioFocusLost

    private void fInicioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fInicioActionPerformed
        // TODO add your handling code here:
        //this.semaforoAlerta();
    }//GEN-LAST:event_fInicioActionPerformed

    private void fFinFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_fFinFocusGained
        // TODO add your handling code here:
        
    }//GEN-LAST:event_fFinFocusGained

    private void fFinFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_fFinFocusLost
        // TODO add your handling code here:
    }//GEN-LAST:event_fFinFocusLost

    private void fFinActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fFinActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_fFinActionPerformed

    private void tCcFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_tCcFocusGained
        // TODO add your handling code here:
       
    }//GEN-LAST:event_tCcFocusGained

    private void tCcFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_tCcFocusLost
        // TODO add your handling code here:
       

    }//GEN-LAST:event_tCcFocusLost

    private void tCcActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tCcActionPerformed
        // TODO add your handling code here:
       

    }//GEN-LAST:event_tCcActionPerformed

    private void tCcKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tCcKeyPressed
        // TODO add your handling code here:
        

    }//GEN-LAST:event_tCcKeyPressed

    private void tCcKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tCcKeyReleased
        // TODO add your handling code here:

    }//GEN-LAST:event_tCcKeyReleased

    private void tCcKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tCcKeyTyped

    }//GEN-LAST:event_tCcKeyTyped

    private void tNameFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_tNameFocusGained
        // TODO add your handling code here:
    }//GEN-LAST:event_tNameFocusGained

    private void tNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tNameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tNameActionPerformed

    private void tPhoneFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_tPhoneFocusGained
        // TODO add your handling code here:
    }//GEN-LAST:event_tPhoneFocusGained

    private void tPhoneActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tPhoneActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tPhoneActionPerformed

    private void tEmailFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_tEmailFocusGained
        // TODO add your handling code here:
    }//GEN-LAST:event_tEmailFocusGained

    private void tEmailActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tEmailActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tEmailActionPerformed

    private void tLastNameFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_tLastNameFocusGained
        // TODO add your handling code here:
    }//GEN-LAST:event_tLastNameFocusGained

    private void tLastNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tLastNameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tLastNameActionPerformed

    private void tAddresFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_tAddresFocusGained
        // TODO add your handling code here:
    }//GEN-LAST:event_tAddresFocusGained

    private void tAddresActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tAddresActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tAddresActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        this.contenedor.verInternalFrameReporte();
    }//GEN-LAST:event_jButton2ActionPerformed

    private void bExportarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bExportarActionPerformed
        try {
            // TODO add your handling code here:
            Utility.exportarExcel(this.table);
        } catch (IOException ex) {
            
        }
    }//GEN-LAST:event_bExportarActionPerformed

    private void tBirthDayFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_tBirthDayFocusGained
        // TODO add your handling code here:
    }//GEN-LAST:event_tBirthDayFocusGained

    private void tBirthDayActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tBirthDayActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tBirthDayActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        this.verRegistro();
    }//GEN-LAST:event_jButton1ActionPerformed

    public void verRegistro(){
        try{
            Date i = (Date)this.fInicio.getValue();
            Date f = (Date)this.fFin.getValue();
            String tt=this.tCc.getText();
            GListPerson gp = new GListPerson();
            GPerson p = gp.getReportPersonRegister(i, f, tt);
            if(p.getName()!=null)
                this.tName.setText(p.getName().toUpperCase());
            if(p.getLastName()!=null)
                this.tLastName.setText(p.getLastName().toUpperCase());
            if(p.getBirthDay()!=null)
                this.tBirthDay.setText(String.valueOf(DateTime.getEdad(p.getBirthDay())) + " Años ");
            if(p.getPhone()!=null)
                this.tPhone.setText(p.getPhone().toUpperCase());
            
            this.tEmail.setText(p.getEmail());
            if(p.getAdress()!=null)
                this.tAddres.setText(p.getAdress().toUpperCase());
            this.model.setNumRows(0);
            for(GRegister l: p.getRegisters()){
                String fecha = DateTime.getDate(l.getDate());
                String hora = DateTime.getTime(l.getTime());
                Object datos[] = {fecha,hora,l.getTemperature(),l.getSymptoms(),l.getOrigin(),
                                  l.getDestination(), l.getObrsevation()};
                this.model.addRow(datos);
            }
            this.lTotal.setVisible(true);
            this.lValorTotal.setVisible(true);
            this.lValorTotal.setText(""+p.getRegisters().size());
            
        }catch(NoResultException e){
            JOptionPane.showMessageDialog(this, "No hay Usuario registrado con el No CC", "ERROR", JOptionPane.ERROR_MESSAGE);
        }
        catch(Exception ex){
            JOptionPane.showMessageDialog(this, ex.getMessage(), "ERROR", JOptionPane.ERROR_MESSAGE);
        }    
    }
    
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bExportar;
    private javax.swing.JFormattedTextField fFin;
    private javax.swing.JFormattedTextField fInicio;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lTotal;
    private javax.swing.JLabel lValorTotal;
    private javax.swing.JTextField tAddres;
    private javax.swing.JTextField tBirthDay;
    private javax.swing.JTextField tCc;
    private javax.swing.JTextField tEmail;
    private javax.swing.JTextField tLastName;
    private javax.swing.JTextField tName;
    private javax.swing.JTextField tPhone;
    private javax.swing.JTable table;
    // End of variables declaration//GEN-END:variables
}
