/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package gov.deajcesar.judisafese.presentation;

import gov.deajcesar.judisafese.logic.GListRegister;
import gov.deajcesar.judisafese.logic.GRegister;
import gov.deajcesar.judisafese.logic.Utility;
import java.io.IOException;
import java.util.Date;
import java.util.List;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author jairo
 */
public class IFReporte extends javax.swing.JInternalFrame {
    private DefaultTableModel model;
    private String titulos[]={"Documento", "Nombre", "Apellido","Fecha", "Temp","Sintomas", "Origen", "Destino", "Observacion"};
    private String datos[][]={null,null, null,null,null};
    private JFPrincipal contenedor;
    
    /**
     * Creates new form IFReporte
     */
    public IFReporte() {
        initComponents();
        this.model = new DefaultTableModel(datos, titulos);
        this.table.setModel(this.model);
        this.lTotal.setVisible(false);
        this.lValorTotal.setVisible(false);
    }

    public void setContenedor(JFPrincipal contenedor) {
        this.contenedor = contenedor;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        fInicio = new javax.swing.JFormattedTextField();
        jLabel2 = new javax.swing.JLabel();
        fFin = new javax.swing.JFormattedTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        table = new javax.swing.JTable();
        jButton1 = new javax.swing.JButton();
        jLabel10 = new javax.swing.JLabel();
        tTmp = new javax.swing.JFormattedTextField();
        jLabel14 = new javax.swing.JLabel();
        lTotal = new javax.swing.JLabel();
        lValorTotal = new javax.swing.JLabel();
        jButton2 = new javax.swing.JButton();
        bExportar = new javax.swing.JButton();

        setTitle("Reportes de ingreso");
        setPreferredSize(new java.awt.Dimension(1051, 726));

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        jLabel1.setText("Fecha Inicio (*) : ");

        fInicio.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        fInicio.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.DateFormatter()));
        fInicio.setToolTipText("dd/mm/yyyy");
        fInicio.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        fInicio.setPreferredSize(new java.awt.Dimension(60, 28));
        fInicio.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                fInicioFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                fInicioFocusLost(evt);
            }
        });
        fInicio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fInicioActionPerformed(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        jLabel2.setText("Fecha Fin (*) : ");

        fFin.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        fFin.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.DateFormatter()));
        fFin.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        fFin.setPreferredSize(new java.awt.Dimension(60, 28));
        fFin.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                fFinFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                fFinFocusLost(evt);
            }
        });
        fFin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fFinActionPerformed(evt);
            }
        });

        table.setAutoCreateRowSorter(true);
        table.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        table.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        table.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null}
            },
            new String [] {
                "No Documento", "Nombre", "Apellido", "Temperatura", "Sintomas", "Origen", "Destino", "Observacion"
            }
        ));
        table.setAutoResizeMode(javax.swing.JTable.AUTO_RESIZE_ALL_COLUMNS);
        jScrollPane1.setViewportView(table);

        jButton1.setText("Buscar");
        jButton1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jLabel10.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        jLabel10.setText("Temp:");

        tTmp.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        tTmp.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter(new java.text.DecimalFormat("#0.00"))));
        tTmp.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        tTmp.setPreferredSize(new java.awt.Dimension(60, 28));
        tTmp.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                tTmpFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                tTmpFocusLost(evt);
            }
        });
        tTmp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tTmpActionPerformed(evt);
            }
        });

        jLabel14.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        jLabel14.setText("° C");

        lTotal.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lTotal.setText("Registros encontrados:");

        lValorTotal.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lValorTotal.setText("jLabel4");

        jButton2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gov/deajcesar/judisafese/resources/paciente.png"))); // NOI18N
        jButton2.setText("Ingresos por CC");
        jButton2.setIconTextGap(10);
        jButton2.setPreferredSize(new java.awt.Dimension(163, 40));
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        bExportar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gov/deajcesar/judisafese/resources/excel.png"))); // NOI18N
        bExportar.setText("Exportar");
        bExportar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bExportarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(1, 1, 1)
                        .addComponent(fInicio, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(fFin, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(40, 40, 40)
                        .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(tTmp, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel14)
                        .addGap(43, 43, 43)
                        .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                            .addComponent(lTotal, javax.swing.GroupLayout.PREFERRED_SIZE, 175, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(lValorTotal, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(bExportar, javax.swing.GroupLayout.PREFERRED_SIZE, 124, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 174, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 978, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(47, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(12, 12, 12)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(fInicio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(fFin, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(tTmp, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jLabel14, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 590, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 14, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(lTotal)
                        .addComponent(lValorTotal))
                    .addComponent(jButton2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(bExportar, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void fInicioFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_fInicioFocusGained
        // TODO add your handling code here:
    }//GEN-LAST:event_fInicioFocusGained

    private void fInicioFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_fInicioFocusLost
        // TODO add your handling code here:
    }//GEN-LAST:event_fInicioFocusLost

    private void fInicioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fInicioActionPerformed
        // TODO add your handling code here:
        //this.semaforoAlerta();
    }//GEN-LAST:event_fInicioActionPerformed

    private void fFinFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_fFinFocusGained
        // TODO add your handling code here:
    }//GEN-LAST:event_fFinFocusGained

    private void fFinFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_fFinFocusLost
        // TODO add your handling code here:
    }//GEN-LAST:event_fFinFocusLost

    private void fFinActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fFinActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_fFinActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        this.verRegistro();
    }//GEN-LAST:event_jButton1ActionPerformed

    private void tTmpFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_tTmpFocusGained
        // TODO add your handling code here:
        
    }//GEN-LAST:event_tTmpFocusGained

    private void tTmpFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_tTmpFocusLost
        // TODO add your handling code here:
        
    }//GEN-LAST:event_tTmpFocusLost

    private void tTmpActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tTmpActionPerformed
        // TODO add your handling code here:
        //this.semaforoAlerta();
        
    }//GEN-LAST:event_tTmpActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        this.contenedor.verInternalFrameReporteCC();
    }//GEN-LAST:event_jButton2ActionPerformed

    private void bExportarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bExportarActionPerformed
        // TODO add your handling code here:
        try {
            // TODO add your handling code here:
            Utility.exportarExcel(this.table);
        } catch (IOException ex) {
        }
    }//GEN-LAST:event_bExportarActionPerformed

    public void verRegistro(){
        try{
            Date i = (Date)this.fInicio.getValue();
            Date f = (Date)this.fFin.getValue();
            double tmp=0;
            String tt=this.tTmp.getText();
            if(!tt.trim().isEmpty())
                tmp = Double.parseDouble(this.tTmp.getValue().toString());
            GListRegister gr = new GListRegister();
            List<GRegister> lista = gr.getReportDayTmp(i, f, tmp);
            this.model.setNumRows(0);
            for(GRegister l: lista){
                String fecha = DateTime.getDate(l.getDate());
                Object datos[] = {l.getPerson().getCc(), l.getPerson().getName(), l.getPerson().getLastName(),
                                  fecha,l.getTemperature(),l.getSymptoms(),l.getOrigin(),
                                  l.getDestination(), l.getObrsevation()};
                this.model.addRow(datos);
            }
            this.lTotal.setVisible(true);
            this.lValorTotal.setVisible(true);
            this.lValorTotal.setText(""+lista.size());
            
        }catch(Exception ex){
            JOptionPane.showMessageDialog(this, ex.getMessage(), "ERROR", JOptionPane.ERROR_MESSAGE);
        }    
    }
    
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bExportar;
    private javax.swing.JFormattedTextField fFin;
    private javax.swing.JFormattedTextField fInicio;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lTotal;
    private javax.swing.JLabel lValorTotal;
    private javax.swing.JFormattedTextField tTmp;
    private javax.swing.JTable table;
    // End of variables declaration//GEN-END:variables
}
