/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package gov.deajcesar.judisafese.presentation;
import gov.deajcesar.judisafese.logic.GListPerson;
import gov.deajcesar.judisafese.logic.GListRegister;
import gov.deajcesar.judisafese.logic.GPerson;
import gov.deajcesar.judisafese.logic.GRegister;
import java.awt.Color;
import java.awt.KeyboardFocusManager;
import java.awt.event.KeyEvent;
import java.sql.SQLException;
import java.util.Calendar;
import java.util.Date;
import javax.persistence.NoResultException;
import javax.swing.JOptionPane;

/**
 *
 * @author jairo
 */
public class IFRegistro extends javax.swing.JInternalFrame implements Runnable {
    private GPerson gp;
    private boolean existe;
    private String busqueda;
    private Thread reloj;
    /**
     * Creates new form NewJInternalFrame
     */
    public IFRegistro() {
        initComponents();
        this.tSymptoms.setLineWrap(true);
        this.tObs.setLineWrap(true);
        this.tDateTime.setText(Calendar.getInstance().getTime().toString());
        this.reloj = new Thread(this);
        this.reloj.start();
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        tCc = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        tName = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        tLastName = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        tPhone = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        tEmail = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        tAddres = new javax.swing.JTextField();
        jPanel1 = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        tDateTime = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        tAlerta = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tSymptoms = new javax.swing.JTextArea();
        jLabel11 = new javax.swing.JLabel();
        tOrigin = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        tDestiny = new javax.swing.JTextField();
        jLabel13 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        tObs = new javax.swing.JTextArea();
        bCancel = new javax.swing.JButton();
        bSave = new javax.swing.JButton();
        tTmp = new javax.swing.JFormattedTextField();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();

        setTitle("Registro ingreso de visitantes");

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        jLabel1.setText("No Documento (*) : ");

        tCc.setBackground(new java.awt.Color(255, 255, 204));
        tCc.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        tCc.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        tCc.setPreferredSize(new java.awt.Dimension(70, 28));
        tCc.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                tCcFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                tCcFocusLost(evt);
            }
        });
        tCc.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tCcActionPerformed(evt);
            }
        });
        tCc.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                tCcKeyPressed(evt);
            }
            public void keyReleased(java.awt.event.KeyEvent evt) {
                tCcKeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                tCcKeyTyped(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        jLabel2.setText("Nombres (*) : ");

        tName.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        tName.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        tName.setPreferredSize(new java.awt.Dimension(60, 28));
        tName.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                tNameFocusGained(evt);
            }
        });
        tName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tNameActionPerformed(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        jLabel3.setText("Apellido  (*) : ");

        tLastName.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        tLastName.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        tLastName.setPreferredSize(new java.awt.Dimension(60, 28));
        tLastName.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                tLastNameFocusGained(evt);
            }
        });
        tLastName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tLastNameActionPerformed(evt);
            }
        });

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        jLabel4.setText("No celular: ");

        tPhone.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        tPhone.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        tPhone.setPreferredSize(new java.awt.Dimension(60, 28));
        tPhone.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                tPhoneFocusGained(evt);
            }
        });
        tPhone.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tPhoneActionPerformed(evt);
            }
        });

        jLabel5.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        jLabel5.setText("Email:");

        tEmail.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        tEmail.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        tEmail.setPreferredSize(new java.awt.Dimension(60, 28));
        tEmail.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                tEmailFocusGained(evt);
            }
        });
        tEmail.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tEmailActionPerformed(evt);
            }
        });

        jLabel6.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        jLabel6.setText("Dir. residencia: ");

        tAddres.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        tAddres.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        tAddres.setPreferredSize(new java.awt.Dimension(60, 28));
        tAddres.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                tAddresFocusGained(evt);
            }
        });
        tAddres.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tAddresActionPerformed(evt);
            }
        });

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 16))); // NOI18N

        jLabel7.setBackground(new java.awt.Color(0, 0, 102));
        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel7.setText("Datos de Ingreso");
        jLabel7.setOpaque(true);

        jLabel8.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        jLabel8.setText("Fecha y Hora : ");

        tDateTime.setEditable(false);
        tDateTime.setBackground(new java.awt.Color(153, 255, 255));
        tDateTime.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        tDateTime.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        tDateTime.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        tDateTime.setPreferredSize(new java.awt.Dimension(60, 28));

        jLabel9.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        jLabel9.setText("Sintomas (*) :");

        tAlerta.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        tAlerta.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        tAlerta.setPreferredSize(new java.awt.Dimension(60, 28));
        tAlerta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tAlertaActionPerformed(evt);
            }
        });

        jLabel10.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        jLabel10.setText("Temp (*) :");

        tSymptoms.setColumns(20);
        tSymptoms.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        tSymptoms.setRows(3);
        tSymptoms.setTabSize(5);
        tSymptoms.setWrapStyleWord(true);
        tSymptoms.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));
        tSymptoms.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                tSymptomsFocusGained(evt);
            }
        });
        tSymptoms.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                tSymptomsKeyPressed(evt);
            }
            public void keyReleased(java.awt.event.KeyEvent evt) {
                tSymptomsKeyReleased(evt);
            }
        });
        jScrollPane1.setViewportView(tSymptoms);

        jLabel11.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        jLabel11.setText("Origen (*) : ");

        tOrigin.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        tOrigin.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        tOrigin.setPreferredSize(new java.awt.Dimension(60, 28));
        tOrigin.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                tOriginFocusGained(evt);
            }
        });
        tOrigin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tOriginActionPerformed(evt);
            }
        });

        jLabel12.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        jLabel12.setText("Destino (*) :");

        tDestiny.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        tDestiny.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        tDestiny.setPreferredSize(new java.awt.Dimension(60, 28));
        tDestiny.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                tDestinyFocusGained(evt);
            }
        });
        tDestiny.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tDestinyActionPerformed(evt);
            }
        });

        jLabel13.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        jLabel13.setText("Observacion: ");

        tObs.setColumns(20);
        tObs.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        tObs.setLineWrap(true);
        tObs.setRows(3);
        tObs.setTabSize(5);
        tObs.setWrapStyleWord(true);
        tObs.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));
        tObs.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                tObsFocusGained(evt);
            }
        });
        tObs.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                tObsKeyPressed(evt);
            }
            public void keyReleased(java.awt.event.KeyEvent evt) {
                tObsKeyReleased(evt);
            }
        });
        jScrollPane2.setViewportView(tObs);

        bCancel.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        bCancel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gov/deajcesar/judisafese/resources/CANCELAR.png"))); // NOI18N
        bCancel.setText("Cancelar");
        bCancel.setIconTextGap(20);
        bCancel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bCancelActionPerformed(evt);
            }
        });

        bSave.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        bSave.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gov/deajcesar/judisafese/resources/save_78348.png"))); // NOI18N
        bSave.setText("Guardar");
        bSave.setIconTextGap(20);
        bSave.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bSaveActionPerformed(evt);
            }
        });

        tTmp.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        tTmp.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter(new java.text.DecimalFormat("#0.00"))));
        tTmp.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        tTmp.setPreferredSize(new java.awt.Dimension(60, 28));
        tTmp.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                tTmpFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                tTmpFocusLost(evt);
            }
        });
        tTmp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tTmpActionPerformed(evt);
            }
        });

        jLabel14.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        jLabel14.setText("° C");

        jLabel15.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        jLabel15.setText("( * ) : Datos Obligatorios");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel13)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGap(0, 0, Short.MAX_VALUE)
                                        .addComponent(jLabel8)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(tDateTime, javax.swing.GroupLayout.PREFERRED_SIZE, 303, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(jLabel9)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 18, Short.MAX_VALUE)
                                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 839, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGap(32, 32, 32))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jLabel11, javax.swing.GroupLayout.DEFAULT_SIZE, 116, Short.MAX_VALUE)
                                    .addComponent(jLabel12, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(tOrigin, javax.swing.GroupLayout.PREFERRED_SIZE, 839, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(tDestiny, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 839, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(32, 32, 32))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel10, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGap(18, 18, 18)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 838, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(tTmp, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jLabel14)
                                        .addGap(29, 29, 29)
                                        .addComponent(tAlerta, javax.swing.GroupLayout.PREFERRED_SIZE, 252, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGap(33, 33, 33))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel15, javax.swing.GroupLayout.PREFERRED_SIZE, 515, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(bSave, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(bCancel, javax.swing.GroupLayout.PREFERRED_SIZE, 167, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(37, 37, 37))))))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jLabel7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(32, 32, 32))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tDateTime, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(16, 16, 16)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(tTmp, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jLabel14, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(tAlerta, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel9, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(tOrigin, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(tDestiny, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel13, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(bCancel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(bSave, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel15)))
                .addGap(14, 14, 14))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(tCc, javax.swing.GroupLayout.PREFERRED_SIZE, 167, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(tName, javax.swing.GroupLayout.DEFAULT_SIZE, 300, Short.MAX_VALUE)
                                    .addComponent(tPhone, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addGap(41, 41, 41)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(tLastName, javax.swing.GroupLayout.DEFAULT_SIZE, 348, Short.MAX_VALUE)
                                    .addComponent(tEmail, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                            .addComponent(tAddres, javax.swing.GroupLayout.PREFERRED_SIZE, 462, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(28, 28, 28)))
                .addGap(30, 30, 30))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(1, 1, 1)
                        .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, 29, Short.MAX_VALUE))
                    .addComponent(tCc, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(tName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(tLastName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(tPhone, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel5)
                        .addComponent(tEmail, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(tAddres, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(63, 63, 63)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void bSaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bSaveActionPerformed
        // TODO add your handling code here:
        this.regRegister();
    }//GEN-LAST:event_bSaveActionPerformed

    private void tCcKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tCcKeyReleased
        // TODO add your handling code here:
        
        
    }//GEN-LAST:event_tCcKeyReleased

    private void tCcActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tCcActionPerformed
        // TODO add your handling code here:
        this.buscar();
        this.asignarFoco(1);
        
    }//GEN-LAST:event_tCcActionPerformed

    private void tNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tNameActionPerformed
            // TODO add your handling code here:
        this.asignarFoco(2);
    }//GEN-LAST:event_tNameActionPerformed

    private void tLastNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tLastNameActionPerformed
            // TODO add your handling code here:
            this.asignarFoco(3);
    }//GEN-LAST:event_tLastNameActionPerformed

    private void tPhoneActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tPhoneActionPerformed
        // TODO add your handling code here:
        this.asignarFoco(4);
    }//GEN-LAST:event_tPhoneActionPerformed

    private void tEmailActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tEmailActionPerformed
        // TODO add your handling code here:
        this.asignarFoco(5);
    }//GEN-LAST:event_tEmailActionPerformed

    private void tAddresActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tAddresActionPerformed
        // TODO add your handling code here:
       this.asignarFoco(6);
    }//GEN-LAST:event_tAddresActionPerformed

    private void tAlertaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tAlertaActionPerformed
        // TODO add your handling code here:
       this.asignarFoco(7); 
    }//GEN-LAST:event_tAlertaActionPerformed

    private void tSymptomsKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tSymptomsKeyReleased
        // TODO add your handling code here:
        
    }//GEN-LAST:event_tSymptomsKeyReleased

    private void tOriginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tOriginActionPerformed
        // TODO add your handling code here:
        this.asignarFoco(9);
    }//GEN-LAST:event_tOriginActionPerformed

    private void tDestinyActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tDestinyActionPerformed
        // TODO add your handling code here:
        this.asignarFoco(10);
    }//GEN-LAST:event_tDestinyActionPerformed

    private void tObsKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tObsKeyReleased
        // TODO add your handling code here:
        
        
    }//GEN-LAST:event_tObsKeyReleased

    private void tObsKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tObsKeyPressed
        // TODO add your handling code here:
        if(evt.getKeyCode()==KeyEvent.VK_ENTER){
            this.asignarFoco(11);
        }
        
    }//GEN-LAST:event_tObsKeyPressed

    private void tSymptomsKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tSymptomsKeyPressed
        // TODO add your handling code here:
        if(evt.getKeyCode()==KeyEvent.VK_ENTER){
            this.asignarFoco(8);
        }
        
    }//GEN-LAST:event_tSymptomsKeyPressed

    private void bCancelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bCancelActionPerformed
        // TODO add your handling code here:
        this.limpiar();
    }//GEN-LAST:event_bCancelActionPerformed

    private void tTmpActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tTmpActionPerformed
        // TODO add your handling code here:
        //this.semaforoAlerta();
        this.asignarFoco(7);
    }//GEN-LAST:event_tTmpActionPerformed

    private void tCcFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_tCcFocusLost
        // TODO add your handling code here:
        if(this.busqueda!=null){
            if(!this.busqueda.equals(this.tCc.getText().trim())){
                this.buscar();
                this.asignarFoco(0);
            }
        }
            
    }//GEN-LAST:event_tCcFocusLost

    private void tTmpFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_tTmpFocusLost
        // TODO add your handling code here:
        if(!this.tTmp.getText().trim().isEmpty())
            this.semaforoAlerta();
    }//GEN-LAST:event_tTmpFocusLost

    private void tCcKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tCcKeyPressed
        // TODO add your handling code here:
        this.tCc.setFocusTraversalKeys(KeyboardFocusManager.FORWARD_TRAVERSAL_KEYS,
                java.util.Collections.EMPTY_SET);
        if (evt.getKeyCode() == KeyEvent.VK_TAB) {
            this.buscar();
            this.asignarFoco(0);
        }
        
    }//GEN-LAST:event_tCcKeyPressed

    private void tCcKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tCcKeyTyped
      
    }//GEN-LAST:event_tCcKeyTyped

    private void tSymptomsFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_tSymptomsFocusGained
        // TODO add your handling code here:
        if(this.tSymptoms.getText().trim().isEmpty()){
                this.tSymptoms.setText(null);
        }
        else
            this.seleccionarTexto(7);
    }//GEN-LAST:event_tSymptomsFocusGained

    private void tObsFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_tObsFocusGained
        // TODO add your handling code here:
            if(this.tObs.getText().trim().isEmpty()){
                this.tObs.setText(null);
            }
            else
                this.seleccionarTexto(10);
           
    }//GEN-LAST:event_tObsFocusGained

    private void tCcFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_tCcFocusGained
        // TODO add your handling code here:
        this.busqueda=this.tCc.getText().trim();
        this.seleccionarTexto(0);
    }//GEN-LAST:event_tCcFocusGained

    private void tNameFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_tNameFocusGained
        // TODO add your handling code here:
        this.seleccionarTexto(1);
    }//GEN-LAST:event_tNameFocusGained

    private void tLastNameFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_tLastNameFocusGained
        // TODO add your handling code here:
        this.seleccionarTexto(2);
    }//GEN-LAST:event_tLastNameFocusGained

    private void tPhoneFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_tPhoneFocusGained
        // TODO add your handling code here:
        this.seleccionarTexto(3);
    }//GEN-LAST:event_tPhoneFocusGained

    private void tEmailFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_tEmailFocusGained
        // TODO add your handling code here:
        this.seleccionarTexto(4);
    }//GEN-LAST:event_tEmailFocusGained

    private void tAddresFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_tAddresFocusGained
        // TODO add your handling code here:
        this.seleccionarTexto(5);
    }//GEN-LAST:event_tAddresFocusGained

    private void tTmpFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_tTmpFocusGained
        // TODO add your handling code here:
        this.seleccionarTexto(6);
    }//GEN-LAST:event_tTmpFocusGained

    private void tOriginFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_tOriginFocusGained
        // TODO add your handling code here:
        this.seleccionarTexto(8);
    }//GEN-LAST:event_tOriginFocusGained

    private void tDestinyFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_tDestinyFocusGained
        // TODO add your handling code here:
        this.seleccionarTexto(9);
    }//GEN-LAST:event_tDestinyFocusGained
    
    public void seleccionarTexto(int n){
        switch (n) {
            case 0:
                this.tCc.selectAll();
                this.tCc.getSelectedText();
                break;
            case 1:
                this.tName.selectAll();
                this.tName.getSelectedText();
                break;
            case 2:
                this.tLastName.selectAll();
                this.tLastName.getSelectedText();
                break;
            case 3:
                this.tPhone.selectAll();
                this.tPhone.getSelectedText();
                break;
            case 4:
                this.tEmail.selectAll();
                this.tEmail.getSelectedText();
                break;
            case 5:
                this.tAddres.selectAll();
                this.tAddres.getSelectedText();
                break;
            case 6:
                this.tTmp.selectAll();
                this.tTmp.getSelectedText();
                break;
            case 7:
                this.tSymptoms.selectAll();
                this.tSymptoms.getSelectedText();
                break;
            case 8:
                this.tOrigin.selectAll();
                this.tOrigin.getSelectedText();
                break;
            case 9:
                this.tDestiny.selectAll();
                this.tDestiny.getSelectedText();
                break;
            case 10:
                this.tObs.selectAll();
                this.tObs.getSelectedText();
                break;
            default:
                break;
        }
    }
    public void asignarFoco(int n){
       
        switch (n) {
            case 0:
                this.tCc.grabFocus();
                if(this.tCc.getText().trim().isEmpty())
                    break;
            case 1:
               this.tName.grabFocus();
               if(this.tName.getText().trim().isEmpty())
                break;
            case 2:
                this.tLastName.grabFocus();
                if(this.tLastName.getText().trim().isEmpty())
                break;
            case 3:
                this.tPhone.grabFocus();
                if(this.tPhone.getText().trim().isEmpty())
                break;
            case 4:
                this.tEmail.grabFocus();
                if(this.tEmail.getText().trim().isEmpty())
                break;
            case 5:
                this.tAddres.grabFocus();
                if(this.tAddres.getText().trim().isEmpty())
                break;
            case 6:
                this.tTmp.grabFocus();
                if(this.tTmp.getText().trim().isEmpty())
                break;
            case 7:
                this.tSymptoms.grabFocus();
                if(this.tSymptoms.getText().trim().isEmpty())
                break;
            case 8:
                this.tOrigin.grabFocus();
                if(this.tOrigin.getText().trim().isEmpty())
                break;
            case 9:
                this.tDestiny.grabFocus();
                if(this.tDestiny.getText().trim().isEmpty())
                break;
            case 10:
                this.tObs.grabFocus();
                if(this.tObs.getText().trim().isEmpty())
                break;
            case 11:
                this.bSave.grabFocus();
                break;
            default:
                break;
        }
    }
    
    public void buscar(){
        String cc = this.tCc.getText();
        this.limpiar();
        this.tCc.setText(cc);
        this.findPerson();
    }
    public void findPerson(){
        
        String cc = this.tCc.getText();
        GListPerson gl = new GListPerson();
        
        try {
            this.gp = gl.getFindPerson(cc);
            this.existe=true;
            this.tName.setText(this.gp.getName().toUpperCase());
            if(this.gp.getLastName()!=null)
                this.tLastName.setText(this.gp.getLastName().toUpperCase());
            if(this.gp.getPhone()!=null)
                this.tPhone.setText(this.gp.getPhone().toUpperCase());
            if(this.gp.getEmail()!=null)
                this.tEmail.setText(this.gp.getEmail());
            if(this.gp.getAdress()!=null)
                this.tAddres.setText(this.gp.getAdress().toUpperCase());
            
        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(this, ex.toString(), "ERROR", JOptionPane.CANCEL_OPTION);
        }catch(NoResultException ex){
            this.existe=false;
        }
    }
    
    public void semaforoAlerta(){
        String tmp=this.tTmp.getText();
        double tm = Double.parseDouble(tmp.replace(',', '.'));
        if(tm<37){
            this.tAlerta.setBackground(Color.GREEN);
        }
        else if(tm<37.8){
            this.tAlerta.setBackground(Color.ORANGE);
        }
        else{
            this.tAlerta.setBackground(Color.red);
        }
    }
    public void regRegister(){
       try{ 
            String destiny=this.tDestiny.getText();
            String obs=this.tObs.getText();
            String origin=this.tOrigin.getText();
            String symptoms=this.tSymptoms.getText();
            double tmp;
            if(this.tTmp.getText().trim().isEmpty())
                tmp=0;
            else
                tmp= Double.parseDouble(this.tTmp.getText().replace(',', '.'));
            Date date= Calendar.getInstance().getTime();
            Date time = Calendar.getInstance().getTime();
            GRegister gr;
            
            String cc = this.tCc.getText();
            String name = this.tName.getText();
            String lname = this.tLastName.getText();
            String phone = this.tPhone.getText();
            String email = this.tEmail.getText();
            String dir = this.tAddres.getText();
            
            if(!this.existe)
                this.gp = new GPerson(cc, name, lname, phone, email, dir);
            else{
                this.gp.setName(name);
                this.gp.setLastName(lname);
                this.gp.setPhone(phone);
                this.gp.setEmail(email);
                this.gp.setAdress(dir);
            }
            gr = new GRegister(this.gp, date, time, tmp, symptoms, origin, destiny, obs);
            this.gp.addRegister(gr);
            if(gr.validate() ){
                GListPerson lp = new GListPerson();
                if(!this.existe){
                   lp.addPerson(this.gp);
                }    
                else{
                    GListRegister lr = new GListRegister();
                    lr.addRegister(gr);
                    lp.updateGPerson(this.gp);
                }
                JOptionPane.showMessageDialog(this, "Registro Exitoso", "MSG", JOptionPane.INFORMATION_MESSAGE);
                this.limpiar();
            }
        } catch (SQLException ex) {
          JOptionPane.showMessageDialog(this, ex.toString(), "ERROR", JOptionPane.CANCEL_OPTION);
         //ex.printStackTrace();
        }
        catch (NumberFormatException ex) {
          JOptionPane.showMessageDialog(this, "La temperatura debe ser un numero", "ERROR", JOptionPane.CANCEL_OPTION);
         //ex.printStackTrace();
          this.tTmp.grabFocus();
        }
        catch (NullPointerException ex) {
          JOptionPane.showMessageDialog(this, ex.getMessage(), "ERROR", JOptionPane.CANCEL_OPTION);
         // this.tTmp.grabFocus();
        }
       
        
    }
    
    public void limpiar(){
        this.tCc.setText(null);
        this.tName.setText(null);
        this.tLastName.setText(null);
        this.tPhone.setText(null);
        this.tEmail.setText(null);
        this.tAddres.setText(null);
        this.tTmp.setText(null);
        this.tSymptoms.setText(null);
        this.tOrigin.setText(null);
        this.tDestiny.setText(null);
        this.tObs.setText(null);
        this.gp=null;
        this.busqueda=null;
        this.tAlerta.setBackground(Color.WHITE);
        this.tCc.grabFocus();
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bCancel;
    private javax.swing.JButton bSave;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTextField tAddres;
    private javax.swing.JTextField tAlerta;
    private javax.swing.JTextField tCc;
    private javax.swing.JTextField tDateTime;
    private javax.swing.JTextField tDestiny;
    private javax.swing.JTextField tEmail;
    private javax.swing.JTextField tLastName;
    private javax.swing.JTextField tName;
    private javax.swing.JTextArea tObs;
    private javax.swing.JTextField tOrigin;
    private javax.swing.JTextField tPhone;
    private javax.swing.JTextArea tSymptoms;
    private javax.swing.JFormattedTextField tTmp;
    // End of variables declaration//GEN-END:variables

    @Override
    public void run() {
        while(this.reloj.isAlive()){
            this.tDateTime.setText(DateTime.getDateTime());
            try {
                Thread.sleep(1000);
            } catch (InterruptedException ex) {
                //Logger.getLogger(IFRegistro.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
    }
}
